# Generated by Django 3.2.25 on 2025-10-31 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('successful_queries', models.IntegerField(default=0)),
                ('failed_queries', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('avg_confidence_score', models.FloatField(default=0.0)),
                ('stock_queries', models.IntegerField(default=0)),
                ('delivery_queries', models.IntegerField(default=0)),
                ('product_info_queries', models.IntegerField(default=0)),
                ('export_requests', models.IntegerField(default=0)),
                ('help_requests', models.IntegerField(default=0)),
                ('timeout_errors', models.IntegerField(default=0)),
                ('sap_errors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.TextField(default='{}')),
                ('sap_query_executed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'chatbot_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('context', models.TextField(default='{}')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatbot_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_key', models.CharField(db_index=True, max_length=255)),
                ('results', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_queries', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'chatbot_query_cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_intent', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('entities', models.TextField(default='{}')),
                ('was_successful', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_logs', to='chatbot.chatmessage')),
            ],
            options={
                'db_table': 'chatbot_intent_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession'),
        ),
        migrations.AddIndex(
            model_name='querycache',
            index=models.Index(fields=['query_key', 'expires_at'], name='chatbot_que_query_k_9ecf0d_idx'),
        ),
    ]
