# Generated by Django 3.2.25 on 2025-11-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatanalytics',
            name='thumbs_down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='thumbs_up_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Thumbs Up'), (-1, 'Thumbs Down')])),
                ('comment', models.TextField(blank=True, help_text='Optional user comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_type', models.CharField(blank=True, choices=[('incorrect_intent', 'Wrong Intent Detected'), ('incorrect_info', 'Incorrect Information'), ('missing_info', 'Missing Information'), ('confusing', 'Response Confusing'), ('slow', 'Too Slow'), ('other', 'Other')], max_length=50)),
                ('message', models.OneToOneField(limit_choices_to={'role': 'assistant'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.chatmessage')),
            ],
            options={
                'db_table': 'chatbot_message_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='messagefeedback',
            index=models.Index(fields=['rating', 'created_at'], name='chatbot_mes_rating_57fd61_idx'),
        ),
    ]
