# Generated by Django 3.2.25 on 2025-11-05 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0002_auto_20251102_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text='Email address where report was sent', max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('csv_filename', models.CharField(max_length=255)),
                ('csv_content', models.TextField(help_text='Full CSV content for audit trail')),
                ('product_count', models.IntegerField(help_text='Number of products in export')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Sent Successfully'), ('failed', 'Failed to Send'), ('blocked', 'Blocked by Policy')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('is_to_personal_email', models.BooleanField(default=False, help_text='Flag if sent to non-company email')),
                ('is_admin_override', models.BooleanField(default=False, help_text='Admin sent to different email address')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_exports', to='chatbot.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Audit Log',
                'verbose_name_plural': 'Email Audit Logs',
                'db_table': 'chatbot_email_audit_log',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailauditlog',
            index=models.Index(fields=['user', 'sent_at'], name='chatbot_ema_user_id_11c4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='emailauditlog',
            index=models.Index(fields=['recipient_email', 'sent_at'], name='chatbot_ema_recipie_8c6414_idx'),
        ),
        migrations.AddIndex(
            model_name='emailauditlog',
            index=models.Index(fields=['is_to_personal_email'], name='chatbot_ema_is_to_p_99fcf0_idx'),
        ),
    ]
