# Generated by Django 3.2.25 on 2025-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20251105_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailauditlog',
            name='csv_file',
            field=models.FileField(blank=True, help_text='CSV file attachment for download', null=True, upload_to='email_exports/%Y/%m/'),
        ),
    ]
