# Generated by Django 3.2.25 on 2025-11-05 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0004_emailauditlog_csv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Notification message text', max_length=255)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has seen this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_log', models.ForeignKey(help_text='The export this notification is about', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chatbot.emailauditlog')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='export_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Notification',
                'verbose_name_plural': 'Export Notifications',
                'db_table': 'chatbot_export_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exportnotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='chatbot_exp_user_id_354d95_idx'),
        ),
    ]
