# Generated by Django 3.2.25 on 2025-11-04 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(help_text='Primary SKU identifier (e.g., FP906, X0463)', max_length=50, primary_key=True, serialize=False)),
                ('gtin', models.CharField(blank=True, db_index=True, help_text='Global Trade Item Number / Barcode (EAN/UPC)', max_length=14, null=True)),
                ('old_item_number', models.CharField(blank=True, db_index=True, help_text='Legacy SKU reference (e.g., Q5761#1)', max_length=50, null=True)),
                ('label', models.CharField(help_text='Product label/display name', max_length=500)),
                ('product_name', models.CharField(help_text='Full product name', max_length=500)),
                ('catalog_brand', models.CharField(db_index=True, help_text='Brand name (e.g., Arcoroc, Dudson, Chef & Sommelier)', max_length=100)),
                ('catalog_collection', models.CharField(blank=True, db_index=True, help_text='Product collection/line (e.g., Islande, Papillon Green)', max_length=100, null=True)),
                ('family', models.CharField(blank=True, db_index=True, help_text='Product family (e.g., Tableware, Buffetware)', max_length=100, null=True)),
                ('categories', models.TextField(blank=True, help_text='Hierarchical categories (comma-separated)', null=True)),
                ('catalog_category', models.CharField(db_index=True, help_text='Main catalog category (Dinnerware, Glassware, Flatware, etc.)', max_length=100)),
                ('website_subcategories', models.CharField(blank=True, help_text='Website subcategories for navigation', max_length=200, null=True)),
                ('long_description', models.TextField(blank=True, help_text='Detailed product description for marketing', null=True)),
                ('short_description', models.TextField(blank=True, help_text='Brief product description/summary', null=True)),
                ('product_tags', models.TextField(blank=True, help_text='Search tags (comma-separated)', null=True)),
                ('list_price', models.DecimalField(decimal_places=2, help_text='List price per unit (USD)', max_digits=10)),
                ('web_price', models.DecimalField(decimal_places=2, help_text='Website/customer price per unit (USD)', max_digits=10)),
                ('sap_case_qty', models.IntegerField(blank=True, help_text='Base units per case (SAP_Base_Unit_To_CS)', null=True)),
                ('sap_case_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Case gross weight in pounds', max_digits=8, null=True)),
                ('sap_case_volume', models.DecimalField(blank=True, decimal_places=3, help_text='Case volume in cubic feet', max_digits=8, null=True)),
                ('material', models.CharField(blank=True, db_index=True, help_text='Item material (e.g., Vitrified Ceramic, Soda Lime Glass)', max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='Combined dimensions string', max_length=200, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in inches', max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in inches', max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in inches', max_digits=8, null=True)),
                ('capacity', models.CharField(blank=True, help_text='Volume capacity (e.g., 12 oz, 500ml)', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='Product color', max_length=50, null=True)),
                ('thumbnail', models.URLField(blank=True, help_text='Primary product image URL (600x600)', max_length=500, null=True)),
                ('assets', models.TextField(blank=True, help_text='Additional image URLs (comma-separated)', null=True)),
                ('beauty_gallery', models.TextField(blank=True, help_text='Lifestyle/beauty shot URLs (comma-separated)', null=True)),
                ('brand_thumbnail', models.URLField(blank=True, help_text='Brand logo URL', max_length=500, null=True)),
                ('status', models.CharField(help_text='DataFeed status (Draft/Active)', max_length=20)),
                ('catalog_status', models.CharField(help_text='Catalog status (New/Active)', max_length=20)),
                ('is_new_feature', models.BooleanField(db_index=True, default=False, help_text='Featured as new product')),
                ('is_sampleable', models.BooleanField(db_index=True, default=False, help_text='Available for sampling')),
                ('variations', models.TextField(blank=True, help_text='Product variant SKUs (comma-separated)', null=True)),
                ('variation_of', models.CharField(blank=True, help_text='Parent product SKU if this is a variant', max_length=50, null=True)),
                ('related_products', models.TextField(blank=True, help_text='Related product SKUs (comma-separated)', null=True)),
                ('suggested_substitute', models.TextField(blank=True, help_text='Substitute product SKUs (comma-separated)', null=True)),
                ('direct_match', models.TextField(blank=True, help_text='Direct match product SKUs (comma-separated)', null=True)),
                ('created', models.DateField(help_text='Created date in DataFeed')),
                ('last_modified', models.DateField(help_text='Last modified date in DataFeed')),
                ('imported_at', models.DateTimeField(auto_now=True, help_text='Timestamp when imported into our system')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('product_count', models.IntegerField(default=0)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'product_brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('product_count', models.IntegerField(default=0)),
                ('subcategories', models.TextField(blank=True, help_text='Comma-separated subcategories', null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_file', models.CharField(help_text='XML file path or URL', max_length=500)),
                ('products_added', models.IntegerField(default=0)),
                ('products_updated', models.IntegerField(default=0)),
                ('products_total', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_import_logs',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog_brand', 'catalog_category'], name='products_catalog_28dc82_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['material'], name='products_materia_a1405d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog_collection'], name='products_catalog_377980_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['family'], name='products_family_0487a4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new_feature'], name='products_is_new__f7db75_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_sampleable'], name='products_is_samp_6d1e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['last_modified'], name='products_last_mo_c08c96_idx'),
        ),
    ]
