"""
Response generator service for creating natural language responses
Enhanced with DataFeed product catalog integration
"""

import logging
from typing import List, Dict, Optional
from .ollama_client import OllamaClient

logger = logging.getLogger(__name__)

# Try to import ProductService for DataFeed enrichment
try:
    from products.services import ProductService
    PRODUCTS_AVAILABLE = True
except ImportError:
    PRODUCTS_AVAILABLE = False
    logger.warning("ProductService not available - DataFeed enrichment disabled")


class ResponseGenerator:
    """Generate natural language responses from data with DataFeed enrichment"""

    def __init__(self, ollama_client: Optional[OllamaClient] = None):
        """
        Initialize response generator with DataFeed support

        Args:
            ollama_client: Optional OllamaClient instance
        """
        self.ollama = ollama_client or OllamaClient()

    def _enrich_with_datafeed(self, results: List[Dict]) -> List[Dict]:
        """
        Enrich SAP results with DataFeed product data

        Args:
            results: SAP query results

        Returns:
            Enriched results with DataFeed data merged in
        """
        if not PRODUCTS_AVAILABLE or not results:
            return results

        enriched = []

        for item in results:
            # Skip error items
            if 'error' in item:
                enriched.append(item)
                continue

            # Get SKU from SAP result
            sku = item.get('MATNR')
            if not sku:
                enriched.append(item)
                continue

            # Try to get DataFeed data
            try:
                datafeed_data = ProductService.get_product_enrichment(sku)

                if datafeed_data:
                    # Merge DataFeed data into SAP result
                    item['datafeed'] = datafeed_data
                    logger.info(f"[DATAFEED] Enriched product {sku} with catalog data")
            except Exception as e:
                logger.warning(f"[DATAFEED] Failed to enrich product {sku}: {e}")

            enriched.append(item)

        return enriched

    def generate(self, user_query: str, intent: str, results: Optional[List[Dict]],
                 context: Dict = None, field_requested: str = None) -> str:
        """
        Generate appropriate response based on intent and data using LLM
        Now with DataFeed product enrichment

        Args:
            user_query: Original user question
            intent: The classified intent
            results: SAP query results or other data
            context: Conversation context
            field_requested: Specific field user asked for (upc, brand, delivery, etc.)

        Returns:
            Natural language response generated by LLM with enriched product data
        """
        # ENRICH results with DataFeed catalog data
        if results and isinstance(results, list):
            results = self._enrich_with_datafeed(results)

        # Prepare enhanced system prompt based on intent
        system_prompt = self._build_system_prompt(intent, field_requested)
        logger.info(f"[LLM] Field requested: {field_requested}")
        logger.info(f"[LLM] System prompt: {system_prompt[:200]}")

        # Format data for LLM
        data_str = self._format_data_for_llm(results, intent, field_requested)
        logger.info(f"[LLM] Data sent to LLM: {data_str[:300]}")

        # Add context if available
        context_str = ""
        if context:
            if context.get('selected_plant'):
                context_str += f"Plant: {context['selected_plant']}\n"
            if context.get('export_format'):
                context_str += f"Export format: {context['export_format']}\n"

        # OPTIMIZATION: For specific field requests (image, UPC, price, sample), skip LLM and use templates
        # This ensures proper formatting (e.g., image markdown, URLs) and is faster
        fields_with_templates = ['image', 'upc', 'price', 'list_price', 'web_price', 'description',
                                 'category', 'material', 'dimensions', 'collection', 'weight', 'case_pack', 'sample']
        if field_requested in fields_with_templates and results:
            logger.info(f"[FAST PATH] Using template for field '{field_requested}' (skipping LLM)")
            return self._generate_specific_field_response(results, field_requested)

        # Build prompt for LLM - natural, conversational format
        prompt = f"""User asked: {user_query}

{context_str}{data_str}

Please answer naturally and conversationally, as if you're a helpful colleague."""

        # Generate response using Ollama with low temperature for factual, accurate responses
        response = self.ollama.generate(prompt, system_prompt, temperature=0.2, max_tokens=200)
        logger.info(f"[LLM] Raw LLM response: {response[:200] if response else 'None'}")

        # Clean up response - remove any JSON artifacts
        if response:
            # Remove markdown code blocks
            response = response.replace('```json', '').replace('```', '').strip()
            # Remove any JSON-like structures at the start
            if response.startswith('{') or response.startswith('['):
                # Find where actual response starts
                lines = response.split('\n')
                for i, line in enumerate(lines):
                    if not line.strip().startswith(('{', '}', '[', ']', '"', ',')) and line.strip():
                        response = '\n'.join(lines[i:])
                        break

        if response:
            return response
        else:
            # Fallback to simple template only if LLM fails
            logger.warning(f"LLM failed to generate response, using fallback for intent: {intent}")
            return self._generate_fallback_response(intent, results, context, field_requested)

    def _build_system_prompt(self, intent: str, field_requested: str = None) -> str:
        """Build system prompt based on intent"""
        base_prompt = """You are a helpful product information assistant for ARC Brand_Delta.

Guidelines:
- Be professional, friendly, and concise
- Answer ONLY what was asked - don't add extra commentary or questions
- Use the EXACT product names from the data provided - never guess or make assumptions
- Use **bold** for important values (numbers, dates, product names)
- Format: "**Product Name** (SKU: 12345)" when mentioning products
- If data shows "Glassware" don't call it "bottles" or "wine" - use the exact category
- Keep responses 1-2 sentences maximum - be direct and helpful
- Never hallucinate details not in the data provided"""

        return base_prompt

    def _format_data_for_llm(self, results: Optional[List[Dict]], intent: str, field_requested: str = None) -> str:
        """Format SAP data for LLM consumption"""
        if not results:
            return "Data: No results found\n"

        # Handle errors
        errors = [r for r in results if 'error' in r]
        valid_results = [r for r in results if 'error' not in r]

        data_str = ""

        if errors:
            data_str += "Errors:\n"
            for err in errors[:3]:
                data_str += f"- Product {err.get('MATNR', 'Unknown')}: {err.get('error', 'Unknown error')}\n"

        if valid_results:
            # Don't mention count for single item queries
            if len(valid_results) > 1:
                data_str += f"\nProducts found: {len(valid_results)}\n"

            # Show first 5 products with relevant fields
            for item in valid_results[:5]:
                product_num = item.get('MATNR', 'Unknown')
                description = item.get('MAKTX', 'Unknown product')

                # Get DataFeed enrichment if available
                datafeed = item.get('datafeed', {})
                if datafeed and datafeed.get('description'):
                    description = datafeed['description']

                # Include relevant fields based on intent
                if intent == 'stock_query':
                    # Include product name for natural responses
                    data_str += f"Product: {description} (SKU: {product_num})\n"
                    data_str += f"  Stock: {item.get('STOCK', 0)} pieces\n"

                elif intent == 'comparison':
                    description = item.get('MAKTX', 'Unknown product')[:50]
                    data_str += f"\nProduct {product_num}: {description}\n"
                    data_str += f"  Stock: {item.get('STOCK', 0)} pieces\n"
                    if item.get('EEIND'):
                        data_str += f"  Next delivery: {item['EEIND']} ({item.get('MNG01', 0)} pieces)\n"

                elif intent == 'delivery_query':
                    data_str += f"\nProduct: {description} (SKU: {product_num})\n"
                    if item.get('EEIND'):
                        data_str += f"  Delivery date: {item['EEIND']}\n"
                        data_str += f"  Delivery quantity: {item.get('MNG01', 0)} pieces\n"
                    else:
                        data_str += f"  No upcoming deliveries\n"
                        data_str += f"  Current stock: {item.get('STOCK', 0)} pieces\n"
                    if item.get('ZMENG', 0) > 0:
                        data_str += f"  In transit: {item['ZMENG']} pieces\n"

                elif intent == 'product_info':
                    # Include product description for natural context
                    data_str += f"\nProduct: {description} (SKU: {product_num})\n"

                    # Add DataFeed fields if available
                    if datafeed:
                        if field_requested == 'description' and datafeed.get('description'):
                            data_str += f"  Description: {datafeed['description']}\n"
                        if field_requested == 'price' and datafeed.get('price'):
                            data_str += f"  List Price: ${datafeed['price'].get('list', 0)}\n"
                            data_str += f"  Web Price: ${datafeed['price'].get('web', 0)}\n"
                        if field_requested == 'brand' and datafeed.get('brand'):
                            data_str += f"  Brand: {datafeed['brand']}\n"
                        if field_requested == 'category' and datafeed.get('category'):
                            data_str += f"  Category: {datafeed['category']}\n"
                        if field_requested == 'material' and datafeed.get('specs', {}).get('material'):
                            data_str += f"  Material: {datafeed['specs']['material']}\n"

                    # SAP fields
                    field_map = {
                        'upc': ('EAN11', 'UPC'),
                        'origin': ('HERKL', 'Origin'),
                        'weight': ('BRGEW', 'Weight'),
                        'vendor_sku': ('BISMT', 'Vendor SKU'),
                        'case_pack': ('UMREZ', 'Case Pack'),
                        'stock': ('STOCK', 'Stock')
                    }

                    if field_requested and field_requested in field_map:
                        sap_field, display_name = field_map[field_requested]
                        value = item.get(sap_field, 'N/A')
                        data_str += f"  {display_name}: {value}\n"

                    # If no specific field, show key info
                    if not field_requested or field_requested == 'all_info':
                        data_str += f"  UPC: {item.get('EAN11', 'N/A')}\n"
                        data_str += f"  Brand: {item.get('ZBRDES', datafeed.get('brand', 'N/A'))}\n"
                        data_str += f"  Origin: {item.get('HERKL', 'N/A')}\n"

            if len(valid_results) > 5:
                data_str += f"\n...and {len(valid_results) - 5} more products\n"

        return data_str

    def _generate_fallback_response(self, intent: str, results: Optional[List[Dict]], context: Dict = None, field_requested: str = None) -> str:
        """Simple fallback when LLM fails"""
        if not results:
            return "I couldn't find any results for your query. Please check the product number and try again."

        # Filter out errors
        valid_results = [r for r in results if 'error' not in r]
        if not valid_results:
            item = results[0]
            return f"I couldn't find product **{item.get('MATNR', 'Unknown')}**. Please verify the product number."

        if len(valid_results) == 1:
            item = valid_results[0]
            product_num = item.get('MATNR', 'Unknown')
            description = item.get('MAKTX', 'Unknown product')

            if intent == 'stock_query':
                stock = item.get('STOCK', 0)
                # Format stock as integer if it's a whole number
                if isinstance(stock, float) and stock.is_integer():
                    stock = int(stock)
                # Shorter, cleaner response without description for follow-ups
                if context and context.get('is_followup'):
                    return f"Product **{product_num}**: **{stock} pieces**"
                else:
                    return f"Product **{product_num}**: **{stock} pieces** in stock"

            elif intent == 'delivery_query':
                if item.get('EEIND'):
                    return f"Product **{product_num}** has a delivery scheduled for **{item['EEIND']}** with **{item.get('MNG01', 0)} pieces**."
                else:
                    return f"Product **{product_num}** has no scheduled deliveries at this time."

            elif intent == 'product_info':
                # If specific field requested, use specific field response
                if field_requested and field_requested != 'all_info':
                    return self._generate_specific_field_response(valid_results, field_requested)
                else:
                    return f"Product **{product_num}**: {description}"

        else:
            # Multiple products
            if intent == 'stock_query':
                # For bulk stock queries, show summary for large results, list for small
                total_found = context.get('total_products_found', len(valid_results)) if context else len(valid_results)

                # Check if results were truncated due to timeout limits
                was_truncated = total_found > len(valid_results)

                # For large result sets (>50), just show summary and let table do the work
                if len(valid_results) > 50:
                    if was_truncated:
                        response = f"Showing first **{len(valid_results)} of {total_found} products**. See table below for details."
                        response += f"\n\n*To get all {total_found} products: Use the 'Download CSV' button below, or ask me to 'Email all results'.*"
                    else:
                        response = f"I found **{len(valid_results)} products**. See table below for details."

                    return response

                # For small result sets (<=50), show the list
                if was_truncated:
                    response = f"Showing first **{len(valid_results)} of {total_found} products**:\n\n"
                else:
                    response = f"I found **{len(valid_results)} products**:\n\n"

                for i, item in enumerate(valid_results, 1):
                    product_num = item.get('MATNR', 'Unknown')
                    stock = item.get('STOCK', 0)
                    description = item.get('MAKTX', '')

                    # Format stock as integer if it's a whole number
                    if isinstance(stock, float) and stock.is_integer():
                        stock = int(stock)

                    # Include description if available
                    if description:
                        response += f"{i}. **{product_num}** ({description[:40]}): **{stock} pieces**\n"
                    else:
                        response += f"{i}. Product **{product_num}**: **{stock} pieces**\n"

                return response
            elif intent == 'product_info' and field_requested and field_requested != 'all_info':
                return self._generate_specific_field_response(valid_results, field_requested)
            return f"I found **{len(valid_results)} products**. Check the table below for details."

    def _generate_stock_response(self, query: str, results: List[Dict], context: Dict, field_requested: str = None) -> str:
        """Generate response for stock queries - DEPRECATED, using LLM now"""

        if not results:
            return "I couldn't find any products matching your query. Please check the product number and try again."

        # Check for errors
        errors = [r for r in results if 'error' in r]
        if errors:
            if len(errors) == len(results):
                # All queries failed
                return f"I encountered an error while checking stock: {errors[0].get('error', 'Unknown error')}"
            # Some queries failed
            error_products = [e.get('MATNR', 'Unknown') for e in errors]
            response = f"I couldn't retrieve data for: {', '.join(error_products)}\n\n"
            results = [r for r in results if 'error' not in r]
        else:
            response = ""

        # Single product response - conversational
        if len(results) == 1:
            product = results[0]
            stock = product.get('STOCK', 0)
            actual = product.get('ACTUAL', 0)
            description = product.get('MAKTX', 'Unknown product')
            product_num = product.get('MATNR', 'Unknown')

            # Start with natural greeting based on stock level
            if stock <= 0:
                response += f"Product **{product_num}** ({description}) is currently **out of stock**. "
            elif stock < 10:
                response += f"Product **{product_num}** ({description}) has **{stock} pieces** in stock - that's pretty low. "
            else:
                response += f"Good news! Product **{product_num}** ({description}) has **{stock} pieces** available. "

            # Add delivery info naturally if available
            if product.get('EEIND'):
                delivery_qty = product.get('MNG01', 0)
                response += f"The next shipment of **{delivery_qty} pieces** is scheduled for **{product['EEIND']}**. "

            # Add in-transit info if available
            if product.get('ZMENG', 0) > 0:
                response += f"There's also **{product['ZMENG']} pieces** currently in transit. "

            # Add recommendation naturally
            if stock <= 0 and not product.get('EEIND'):
                response += "\n\nYou might want to check with purchasing about getting more ordered."
            elif stock < 10 and not product.get('EEIND'):
                response += "\n\nMight be a good idea to place an order soon."

        # Multiple products response
        else:
            response += f"I found **{len(results)} products**. Here's the summary:\n\n"

            # Summary statistics
            total_stock = sum(r.get('STOCK', 0) for r in results)
            in_stock = len([r for r in results if r.get('STOCK', 0) > 0])
            out_of_stock = len(results) - in_stock

            response += f"📊 **Summary**: {in_stock} in stock, {out_of_stock} out of stock\n"
            response += f"📦 **Total Stock**: {total_stock} pieces\n\n"

            # Show first 5 products in detail
            for product in results[:5]:
                stock = product.get('STOCK', 0)
                status = "✅" if stock > 0 else "❌"
                response += f"{status} **{product.get('MATNR', 'Unknown')}**: {stock} pcs"

                if product.get('EEIND'):
                    response += f" (Next: {product['EEIND']})"
                response += "\n"

            if len(results) > 5:
                response += f"\n...and {len(results) - 5} more products. Check the results panel for full details."

        return response

    def _generate_delivery_response(self, query: str, results: List[Dict], context: Dict, field_requested: str = None) -> str:
        """Generate response for delivery queries"""

        if not results:
            return "I couldn't find any delivery information. Please check the product number and try again."

        # Filter products with delivery dates
        with_deliveries = [r for r in results if r.get('EEIND') and 'error' not in r]

        if not with_deliveries:
            if len(results) == 1:
                product = results[0]
                stock = product.get('STOCK', 0)
                product_num = product.get('MATNR', 'Unknown')
                return f"There are no scheduled deliveries for product **{product_num}** right now. Current stock is **{stock} pieces**."
            else:
                return "None of these products have scheduled deliveries at the moment."

        # Single delivery - conversational
        if len(with_deliveries) == 1:
            product = with_deliveries[0]
            product_num = product.get('MATNR', 'Unknown')
            description = product.get('MAKTX', 'Unknown product')
            delivery_date = product['EEIND']
            delivery_qty = product.get('MNG01', 0)

            response = f"Product **{product_num}** ({description}) has a delivery coming on **{delivery_date}** with **{delivery_qty} pieces**. "

            if product.get('ZMENG', 0) > 0:
                response += f"There's also **{product['ZMENG']} pieces** in transit. "

            return response

        # Multiple deliveries - still conversational
        response = f"Here are the upcoming deliveries for your {len(with_deliveries)} products:\n\n"

        # Sort by delivery date if possible
        try:
            with_deliveries.sort(key=lambda x: x.get('EEIND', ''))
        except:
            pass

        for product in with_deliveries[:10]:
            product_num = product.get('MATNR', 'Unknown')
            description = product.get('MAKTX', 'Unknown')[:40]
            delivery_date = product['EEIND']
            delivery_qty = product.get('MNG01', 0)

            response += f"• **{product_num}** ({description}): **{delivery_qty} pieces** on **{delivery_date}**"

            if product.get('ZMENG', 0) > 0:
                response += f" (+ {product['ZMENG']} in transit)"

            response += "\n"

        if len(with_deliveries) > 10:
            response += f"\n...and {len(with_deliveries) - 10} more deliveries scheduled."

        return response

    def _generate_product_info_response(self, query: str, results: List[Dict], context: Dict, field_requested: str = None) -> str:
        """Generate response for product information queries"""

        if not results:
            return "I couldn't find any product information. Please check the product number and try again."

        # Filter out errors
        valid_results = [r for r in results if 'error' not in r]
        if not valid_results:
            return "I encountered an error retrieving product information."

        # SMART FIELD-SPECIFIC RESPONSES
        if field_requested and field_requested != 'all_info':
            return self._generate_specific_field_response(valid_results, field_requested)

        # Full product info response
        response = "📋 **Product Information**:\n\n"

        for product in valid_results[:5]:  # Limit to 5 products
            response += f"**{product.get('MATNR', 'Unknown')}** - {product.get('MAKTX', 'Unknown Description')}\n"
            response += f"• Vendor SKU: {product.get('BISMT', 'N/A')}\n"
            response += f"• Brand: {product.get('ZBRDES', 'N/A')}\n"
            response += f"• Origin: {product.get('HERKL', 'N/A')}\n"
            response += f"• UPC/EAN: {product.get('EAN11', 'N/A')}\n"
            response += f"• Case Pack: {product.get('UMREZ', 'N/A')} units\n"
            response += f"• Case Weight: {product.get('BRGEW', 'N/A')} kg\n"
            response += f"• Type: {product.get('DISMM', 'N/A')}\n"
            response += "\n"

        if len(valid_results) > 5:
            response += f"...and {len(valid_results) - 5} more products."

        # Add truncation notice if results were limited
        if context.get('truncated'):
            total = context.get('total_available', 0)
            response += f"\n\n⚠️ **Showing first {len(valid_results)} of {total} total products**. "
            response += f"To get the complete report, type 'email all results'."

        return response

    def _generate_specific_field_response(self, results: List[Dict], field: str) -> str:
        """Generate response for a specific field request (SAP + DataFeed data)"""
        # SAP field mappings
        sap_field_map = {
            'upc': ('EAN11', 'UPC', 'UPC code'),
            'brand': ('ZBRDES', 'brand', 'brand'),
            'origin': ('HERKL', 'country of origin', 'origin'),
            'weight': ('BRGEW', 'weight', 'weight'),
            'case_pack': ('UMREZ', 'case pack size', 'case pack'),
            'vendor_sku': ('BISMT', 'vendor SKU', 'vendor SKU'),
            'delivery': ('EEIND', 'next delivery date', 'delivery date'),
            'stock': ('STOCK', 'current stock', 'stock')
        }

        # DataFeed field mappings
        datafeed_field_map = {
            'price': ('price', 'price', 'price'),  # General price - handled specially
            'list_price': ('price.list', 'list price', 'list price'),
            'web_price': ('price.web', 'web price', 'web price'),
            'description': ('description', 'description', 'description'),
            'category': ('category', 'category', 'category'),
            'material': ('specs.material', 'material', 'material'),
            'dimensions': ('specs.dimensions', 'dimensions', 'dimensions'),
            'collection': ('collection', 'collection', 'collection'),
            'image': ('images.thumbnail', 'product image', 'image'),
            'sample': ('product_url', 'sample request', 'sample')  # Product URL for sampling
        }

        # Check if this is a DataFeed field
        if field in datafeed_field_map:
            return self._generate_datafeed_field_response(results, field, datafeed_field_map[field])

        # SAP field handling
        if field not in sap_field_map:
            return self._generate_product_info_response("", results, {}, None)

        sap_field, field_name, short_name = sap_field_map[field]

        # Single product - natural conversational response
        if len(results) == 1:
            product = results[0]
            product_num = product.get('MATNR', 'Unknown')
            product_desc = product.get('MAKTX', 'Unknown product')
            field_value = product.get(sap_field, 'N/A')

            logger.info(f"[SPECIFIC FIELD] field={field}, sap_field={sap_field}, value={field_value}, product={product_num}")

            if field_value == 'N/A' or not field_value:
                if field == 'delivery':
                    stock = product.get('STOCK', 0)
                    return f"No upcoming deliveries for **{product_desc}** (SKU: {product_num}). Current stock: **{stock} pieces**."
                return f"I found product {product_num} ({product_desc}), but unfortunately the {field_name} isn't available in the system."

            # Special formatting for delivery dates
            if field == 'delivery':
                delivery_qty = product.get('MNG01', 0)
                response = f"The next delivery for **{product_desc}** is on **{field_value}**"
                if delivery_qty:
                    response += f" with **{delivery_qty} pieces**"
                response += f" (SKU: {product_num})"
                return response

            # Special formatting for stock
            elif field == 'stock':
                return f"We have **{field_value} pieces** of **{product_desc}** in stock (SKU: {product_num})"

            # Generic field response - still friendly
            else:
                response = f"The {field_name} for **{product_num}** is **{field_value}**"
                logger.info(f"[SPECIFIC FIELD RESPONSE] {response}")
                return response

        # Multiple products - still conversational but with list
        response = f"Here's the {field_name} information for your products:\n\n"

        for product in results[:10]:
            product_num = product.get('MATNR', 'Unknown')
            product_desc = product.get('MAKTX', 'Unknown')
            field_value = product.get(sap_field, 'N/A')

            if field_value and field_value != 'N/A':
                response += f"• **{product_num}** ({product_desc}): {field_value}\n"
            else:
                response += f"• **{product_num}** ({product_desc}): Not available\n"

        if len(results) > 10:
            response += f"\n...and {len(results) - 10} more products."

        return response

    def _generate_datafeed_field_response(self, results: List[Dict], field: str, field_info: tuple) -> str:
        """Generate response for DataFeed-specific fields (price, description, etc.)"""
        field_path, field_name, short_name = field_info

        # Helper to extract nested field from datafeed data
        def get_nested_field(data, path):
            keys = path.split('.')
            value = data
            for key in keys:
                if isinstance(value, dict):
                    value = value.get(key)
                else:
                    return None
            return value

        # Single product
        if len(results) == 1:
            product = results[0]
            product_num = product.get('MATNR', 'Unknown')
            datafeed_data = product.get('datafeed', {})

            # DEBUG: Log what we're receiving
            logger.info(f"[DATAFEED DEBUG] Product {product_num}: has datafeed={bool(datafeed_data)}, keys={list(datafeed_data.keys()) if datafeed_data else []}")
            logger.info(f"[DATAFEED DEBUG] Product keys: {list(product.keys())}")

            # Sample field doesn't need datafeed data (uses database fields)
            if not datafeed_data and field != 'sample':
                return f"Product **{product_num}** data is not available from the catalog yet."

            field_value = get_nested_field(datafeed_data, field_path) if datafeed_data else None

            logger.info(f"[DATAFEED FIELD] field={field}, path={field_path}, value={field_value}, product={product_num}")

            # Sample field doesn't use field_value (builds URL from product data)
            if not field_value and field != 'sample':
                return f"The {field_name} for product **{product_num}** is not available in the catalog."

            # Format based on field type
            if field == 'price':
                # General price query - show both
                list_price = datafeed_data.get('price', {}).get('list', 0)
                web_price = datafeed_data.get('price', {}).get('web', 0)
                response = f"**{product_num}** pricing:\n"
                response += f"• List Price: **${list_price:.2f}**\n"
                response += f"• Web Price: **${web_price:.2f}**"
                return response

            elif field == 'list_price':
                # Specific list price query
                list_price = datafeed_data.get('price', {}).get('list', 0)
                return f"The list price for **{product_num}** is **${list_price:.2f}**"

            elif field == 'web_price':
                # Specific web price query
                web_price = datafeed_data.get('price', {}).get('web', 0)
                return f"The web price for **{product_num}** is **${web_price:.2f}**"

            elif field == 'image':
                image_url = field_value
                product_name = datafeed_data.get('name', 'Unknown product')
                response = f"**{product_num}** - {product_name}\n\n"
                response += f"![Product Image]({image_url})"
                return response

            elif field == 'sample':
                # Build product URL from product data
                # Handle both flat (get_product_enrichment) and nested (SAP+datafeed) structures
                from products.services import ProductService

                # Get product name (try both structures)
                product_name = datafeed_data.get('name') if datafeed_data else product.get('name', 'Unknown product')

                # Get SKU (try both MATNR and sku)
                sku = product.get('sku') or product_num

                # Get URL components - try flat structure first, then nested datafeed structure
                # Flat structure (get_product_enrichment): fields at top level
                # Nested structure (SAP+datafeed): fields inside 'datafeed' object
                family = product.get('family') or (datafeed_data.get('family') if datafeed_data else None)
                category = product.get('catalog_category') or (datafeed_data.get('catalog_category') if datafeed_data else None)
                subcategories = product.get('website_subcategories') or (datafeed_data.get('website_subcategories') if datafeed_data else None)
                label = product.get('label') or (datafeed_data.get('label') if datafeed_data else None)

                product_url = ProductService.build_product_url(family, category, subcategories, label)

                response = f"You can request a sample of **{product_name}** (SKU: **{sku}**) here:\n\n"
                response += f"[View Product & Request Sample]({product_url})"
                return response

            elif field == 'description':
                desc = field_value
                if len(desc) > 300:
                    desc = desc[:297] + "..."
                return f"That's the **{desc}** (SKU: {product_num})"

            else:
                return f"The {field_name} for **{product_num}** is **{field_value}**"

        # Multiple products
        response = f"Here's the {field_name} information:\n\n"

        for product in results[:10]:
            product_num = product.get('MATNR', 'Unknown')
            datafeed_data = product.get('datafeed', {})

            if datafeed_data:
                field_value = get_nested_field(datafeed_data, field_path)

                if field_value or field in ['price', 'list_price', 'web_price']:
                    if field == 'price':
                        list_price = datafeed_data.get('price', {}).get('list', 0)
                        web_price = datafeed_data.get('price', {}).get('web', 0)
                        response += f"• **{product_num}**: List ${list_price:.2f}, Web ${web_price:.2f}\n"
                    elif field == 'list_price':
                        list_price = datafeed_data.get('price', {}).get('list', 0)
                        response += f"• **{product_num}**: ${list_price:.2f}\n"
                    elif field == 'web_price':
                        web_price = datafeed_data.get('price', {}).get('web', 0)
                        response += f"• **{product_num}**: ${web_price:.2f}\n"
                    else:
                        response += f"• **{product_num}**: {field_value}\n"
                else:
                    response += f"• **{product_num}**: Not available\n"
            else:
                response += f"• **{product_num}**: Not in catalog\n"

        if len(results) > 10:
            response += f"\n...and {len(results) - 10} more products."

        return response

    def _generate_comparison_response(self, query: str, results: Dict, context: Dict) -> str:
        """Generate response for comparison queries"""

        if isinstance(results, dict) and 'products' in results:
            products = results['products']
            summary = results.get('summary', {})
        else:
            products = results if isinstance(results, list) else []
            summary = {}

        if not products:
            return "I couldn't find any products to compare."

        response = "📊 **Product Comparison**:\n\n"

        # Add summary if available
        if summary:
            response += f"**Overview**: {summary.get('total_products', 0)} products compared\n"
            response += f"• In Stock: {summary.get('in_stock', 0)}\n"
            response += f"• Out of Stock: {summary.get('out_of_stock', 0)}\n"
            response += f"• Total Stock: {summary.get('total_stock', 0)} pieces\n\n"

        # Compare products
        response += "**Stock Levels**:\n"

        # Sort by stock level
        sorted_products = sorted(products, key=lambda x: x.get('STOCK', 0), reverse=True)

        for product in sorted_products[:10]:
            if 'error' not in product:
                stock = product.get('STOCK', 0)
                bar = "🟩" * min(int(stock / 10), 10) if stock > 0 else "🟥"
                response += f"{product.get('MATNR', 'Unknown')}: {bar} {stock} pcs\n"

        if len(sorted_products) > 10:
            response += f"\n...and {len(sorted_products) - 10} more products."

        # Add insights
        if sorted_products:
            highest_stock = sorted_products[0]
            lowest_stock = sorted_products[-1]
            response += f"\n**Insights**:\n"
            response += f"• Highest stock: **{highest_stock.get('MATNR')}** ({highest_stock.get('STOCK', 0)} pcs)\n"
            response += f"• Lowest stock: **{lowest_stock.get('MATNR')}** ({lowest_stock.get('STOCK', 0)} pcs)\n"

        return response

    def _generate_export_response(self, query: str, results: Optional[List[Dict]], context: Dict) -> str:
        """Generate response for export requests"""

        export_format = context.get('export_format', 'excel')

        if not results and not context.get('last_results'):
            return "I don't have any results to export. Please run a search first, then request the export."

        # Count products
        product_count = len(results) if results else 0
        product_text = f"{product_count} product" + ("s" if product_count != 1 else "")

        # Natural, varied responses based on format
        if export_format == 'email':
            return f"I've prepared the data for {product_text}. Click the button below to send it to your email address."
        elif export_format == 'pdf':
            return f"Your PDF report with {product_text} is ready! Click below to download."
        elif export_format == 'csv':
            return f"I've got {product_text} ready for export. Click the download button to get your CSV file."
        else:  # excel / generic
            return f"Your Excel file with {product_text} is ready to download!"

    def _generate_plant_response(self, query: str, context: Dict) -> str:
        """Generate response for plant selection"""

        selected_plant = context.get('selected_plant')
        if selected_plant:
            return f"✅ Plant **{selected_plant}** has been selected. You can now search for products at this location."
        else:
            return "Please select a plant from the available options to continue."

    def generate_help_response(self) -> str:
        """Generate help response"""

        return """🤔 **How can I help you?**

I'm your product availability assistant. Here's what I can do:

**📦 Stock Queries**
• "What's the stock of product 10001?"
• "Check availability for SKU 123456"
• "How many units of 11111, 22222 do we have?"

**🚚 Delivery Information**
• "When is the next delivery for 10001?"
• "What's coming in next week?"
• "Check in-transit quantity for 123"

**📋 Product Details**
• "What's the brand of product 10001?"
• "Show specs for SKU 789"
• "Get UPC code for product 456"

**📊 Comparisons**
• "Compare stock for products 111, 222, 333"
• "Which products have the most stock?"

**💾 Export Options**
• "Email me the results"
• "Download as Excel"
• "Export to PDF"

**Tips**:
• You can check multiple products at once (up to 100)
• Use product numbers (4-8 digits) or vendor SKUs
• I'll remember your selected plant during our conversation

Just type your question naturally, and I'll help you get the information you need!"""

    def generate_greeting_response(self, context: Dict = None) -> str:
        """Generate greeting response"""

        username = context.get('username', 'there') if context else 'there'
        return f"""Hi {username}! I'm here to help you with product availability, stock levels, and delivery information.

What can I look up for you? Just ask me naturally, like:
• "What's the stock of 10001?"
• "When will product G3960 be delivered?"
• "Can you find the UPC for 10002?"

Go ahead and type your question!"""

    def generate_clarification_request(self, intent: str, entities: Dict) -> str:
        """Generate clarification request when information is missing"""

        missing = []

        # Check what's missing based on intent
        if intent in ['stock_query', 'delivery_query', 'product_info', 'comparison']:
            if not entities.get('product_numbers') and not entities.get('vendor_skus'):
                missing.append("product number(s)")

        if intent == 'export_request':
            if not entities.get('export_format'):
                return """How would you like to export the results?
• Type "Excel" for a spreadsheet
• Type "Email" to send to your email
• Type "PDF" for a PDF report"""

        if missing:
            return f"I need the {' and '.join(missing)} to help you. Could you please provide that information?"

        return """I'm not quite sure what you're looking for. Could you please clarify? You can:
• Check stock levels
• View delivery schedules
• Get product information
• Export results

What would you like to do?"""

    def generate_error_response(self, error_type: str = 'generic') -> str:
        """Generate error responses"""

        error_responses = {
            'sap_connection': "⚠️ I'm having trouble connecting to the SAP system. Please try again in a moment.",
            'ollama_connection': "⚠️ I'm experiencing technical difficulties with the AI service. Using basic mode.",
            'timeout': "⏱️ The request is taking longer than expected. Please try again with fewer products.",
            'no_plant_access': "🚫 You don't have access to any plants. Please contact your administrator.",
            'invalid_product': "❌ That doesn't appear to be a valid product number. Product numbers should be 4-8 digits.",
            'generic': "⚠️ Something went wrong. Please try again or contact support if the issue persists."
        }

        return error_responses.get(error_type, error_responses['generic'])