# Generated by Django 2.1.5 on 2019-03-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business',
            field=models.CharField(blank=True, choices=[('BU_A', 'Business Unit A'), ('BU_B', 'Business Unit B')], max_length=10, null=True),
        ),
    ]
