# Generated by Django 2.1.5 on 2019-03-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcheck', '0002_profile_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
