# Generated by Django 2.1.5 on 2023-07-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockcheck', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
